spring:
  profiles:
    active:
      - local
    group:
      local:
        - mail
        - oauth
        - cloud
        - db-local
        - common
      dev:
        - mail
        - oauth
        - cloud
        - db-dev
        - common
    include: oauth, mail, cloud, common, db
