cloud:
  aws:
    ses:
      access-key: ENC(8b1rp/swdalSLvjt3zu7IXEkezBPVib4KGqpAHD1OAE=)
      secret-key: ENC(I8XqdbHRwYF+FWS3AA7iTU+jusJo2oMQ4H/eGtpmfjrMSzfa4ay3BNOoQdvLyP9R0S4AEn4svDY=)
    s3:
      credentials:
        accessKey: ENC(IlmbXknVPL7fdZy7MIQtdc6A3HkW02ILZ9gXvqdpSds=)
        secretKey: ENC(4b9qi8p0FeIFZEZcaRCxTlXJEpJ8FRBEG9EoC3evNtrh12P/+BAti2kBLikyUFJFse2Iz4wGBZM=)
      bucket: ENC(743o2jb4oyIiTHoglXlirxJbM83rY3hC)
      region:
        static: ap-northeast-2
    stack:
      auto: false
